import assert from 'assert';
import { Node, PriorityQueue, WeightedGraph } from '../server/routes/dijkstra';

describe('PriorityQueueNode', function () {
  const expected = {
    value: 'thing',
    priority: 12,
  };

  it('correctly creates Node object', function () {
    const actNode = new Node(expected.value, expected.priority);

    assert.equal(actNode.val, expected.value, `ValueError: expected node value ${expected.value} but found ${actNode.val}`);
    assert.strictEqual(actNode.val, expected.value, `TypeError: expected type ${typeof expected.value} but found ${typeof actNode.val}`);
    assert.equal(actNode.priority, expected.priority, `ValueError: expected node value ${expected.priority} but found ${actNode.priority}`);
    assert.strictEqual(actNode.priority, expected.priority, `TypeError: expected type ${typeof expected.priority} but found ${typeof actNode.priority}`);
  });
});

describe('PriorityQueue', function () {
  const nodes = [
    new Node('thing', 3),
    new Node('yeet', 100),
    new Node('okay', -1),
    new Node('wow', 1),
    new Node('agh', 0),
];

  it('correct initialise PriorityQueue object', function () {
    const newQueue = new PriorityQueue();
    const expQueue = [];

    assert.deepStrictEqual(newQueue.values, expQueue, `ValueError: empty list, '${expQueue}' but found '${newQueue.values}'`);
  });

  it('correctly adds PriorityQueue objects', function () {
    const newQueue = new PriorityQueue();
    newQueue.enqueue(nodes[0].val, nodes[0].priority);
    const expVals = [nodes[0]];

    assert.equal(newQueue.values.length, expVals.length, `ValueError: value lists were of different sizes. Expected ${expVals.length} but got ${newQueue.values.length}`);
    assert.deepStrictEqual(newQueue.values[0], expVals[0], `ValueError: mismatch at index 0, expected ${expVals[0]} but got ${newQueue.values[0]}`)
    assert.deepStrictEqual(newQueue.values, expVals, `ValueError: expected nodes ${expVals} but found ${newQueue.values}`);
  });

  it('correctly orders PriorityQueue objects', function () {
    const newQueue = new PriorityQueue();
    newQueue.enqueue(nodes[2].val, nodes[2].priority); // priority -1
    newQueue.enqueue(nodes[0].val, nodes[0].priority); // priority 3
    newQueue.enqueue(nodes[3].val, nodes[3].priority); // priority 1

    const expQueue1 = [nodes[2], nodes[3], nodes[0]];
    const expQueue2 = [nodes[2], nodes[0], nodes[3]];

    if (newQueue.values[1].priority == expQueue1[1].priority) {
      assert.deepStrictEqual(newQueue.values, expQueue1, `ValueError: expected nodes ${expQueue1} but found ${newQueue.values}`);
    } else {
      assert.deepStrictEqual(newQueue.values, expQueue2, `ValueError: expected nodes ${expQueue2} but found ${newQueue.values}`);
    }
  });

  it('correctly removes and reorders PriorityQueue objects', function () {
    const newQueue = new PriorityQueue();
    newQueue.enqueue(nodes[2].val, nodes[2].priority); // priority -1
    newQueue.enqueue(nodes[0].val, nodes[0].priority); // priority 3
    newQueue.enqueue(nodes[3].val, nodes[3].priority); // priority 1
    newQueue.enqueue(nodes[1].val, nodes[1].priority); // priority 100
    newQueue.enqueue(nodes[4].val, nodes[4].priority); // priority 0

    const expRemoval = [nodes[2], nodes[4], nodes[3], nodes[0], nodes[1]];

    for (let i = 0; i < 5; i++) {
      const nxtVal = newQueue.dequeue()
      assert.deepStrictEqual(nxtVal, expRemoval[i], `ValueError: expected value ${expRemoval[i]} but found ${nxtVal}`);
    }
  });
});

// the following set of tests were generated by Claude
// they were then reviewed to ensure correctness and extended for more complete coverage
describe('WeightedGraph', function () {
  it('Add new vertex to graph', function () {
    const graph = new WeightedGraph();
    const coords = { x: 1, y: 2 }
    graph.addVertex(0, coords);
    assert.deepStrictEqual(graph.adjacencyList[0], [], `Expected an empty list but found ${graph.adjacencyList[0]}`);
    assert.deepStrictEqual(graph.coordMap[0], coords, `Expected the object ${coords} but found ${graph.coordMap[0]}`);
  });

  it('Fail on attempted replacement of existing vertex', function () {
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 1, y: 2 });
    assert.throws(
      () => graph.addVertex(0, { x: 9, y: 9 }),
      /Node with index 0 already existed in the graph\./
    );
  });

  it('Adds an edge between two existing vertices', function () {
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 });
    graph.addVertex(1, { x: 1, y: 1 });
    graph.addEdge(0, 1, 5);
    const expEdge0 = { node: 1, weight: 5 };
    const expEdge1 = { node: 0, weight: 5 };
    assert.deepStrictEqual(graph.adjacencyList[0], [expEdge0], `Expected edge: ${expEdge0} but found ${graph.adjacencyList[0]}`);
    assert.deepStrictEqual(graph.adjacencyList[1], [expEdge1], `Expected edge: ${expEdge1} but found ${graph.adjacencyList[1]}`);
  });

  it('Check raises error for empty/undefined nodes', function () {
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 });
    graph.addVertex(2, { x: 2, y: 2 });
    assert.throws(
      () => graph.dijkstra(0, [2]),
      'Undefined node found in WeightedGraph at index 1.'
    );
  });

  it('Check raises error for empty graph', function () {
    const graph = new WeightedGraph();
    assert.throws(
      () => graph.dijkstra(0, [0]),
      /Couldn't find the starting index 0/
    );
  });

  it('Check for error when no path exists from start to any finish', function () {
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 }); // isolated - no edges
    graph.addVertex(1, { x: 1, y: 0 });
    graph.addVertex(2, { x: 2, y: 0 });
    graph.addVertex(3, { x: 1, y: 1 });
    graph.addVertex(4, { x: 2, y: 1 }); // isolated - no edges
    graph.addEdge(1, 2, 1);
    graph.addEdge(2, 3, 10);
    assert.throws(
      () => graph.dijkstra(1, [0, 4]),
      /Dijkstra's algorithm could not find a path from node 1/
    );
  });

  it('Check for 0-length path when start in finish list', function () {
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 });
    graph.addVertex(1, { x: 1, y: 0 });
    graph.addEdge(0, 1, 5);
    const result = graph.dijkstra(1, [0, 1]);
    assert.deepStrictEqual(result, { waypoints: [1], legDist: 0 }, `Expected a single waypoint with distance=0 but got: ${result}`);
  });

  it('Test Dijkstra\'s algorithm for correctness (single finish, simple)', function () {
    // Graph:
    //   0 --(1)--> 1 --(1)--> 3
    //   0 --(5)--> 2 --(1)--> 3
    // Shortest 0 -> 3 is via 1 (cost 2), not via 2 (cost 6).
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 });
    graph.addVertex(1, { x: 1, y: 0 });
    graph.addVertex(2, { x: 2, y: 0 });
    graph.addVertex(3, { x: 3, y: 0 });
    graph.addEdge(0, 1, 1);
    graph.addEdge(1, 3, 1);
    graph.addEdge(0, 2, 5);
    graph.addEdge(2, 3, 1);

    const result = graph.dijkstra(0, [3]);
    const exp = { waypoints: [0, 1, 3], legDist: 2 };
    assert.deepStrictEqual(result, exp, `Expected: ${exp}\nbut got: ${result}`);
  });

  it('Test Dijkstra\'s algorithm for correctness (multi finish, simple)', function () {
    // Graph:
    //   0 --(1)--> 1 --(3)--> 3
    //   0 --(5)--> 2 --(1)--> 3
    //   0 --(1)--> 1 --(1)--> 4 --(1)--> 5
    // Shortest 0 -> 5 (total 3) is shortest
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 0, y: 0 });
    graph.addVertex(1, { x: 1, y: 0 });
    graph.addVertex(2, { x: 2, y: 0 });
    graph.addVertex(3, { x: 3, y: 0 });
    graph.addVertex(4, { x: 3, y: 1 });
    graph.addVertex(5, { x: 3, y: 2 });
    graph.addEdge(0, 1, 1);
    graph.addEdge(1, 3, 3);
    graph.addEdge(0, 2, 5);
    graph.addEdge(2, 3, 1);
    graph.addEdge(1, 4, 1);
    graph.addEdge(4, 5, 1);

    const result = graph.dijkstra(0, [3, 5]);
    const exp = { waypoints: [0, 1, 4, 5], legDist: 3 }
    assert.deepStrictEqual(result, exp, `Expected: ${exp}\nbut got: ${result}`);
  });

  it('Test Dijkstra\'s algorithm for correctness (complex)', function () {
    /* Graph:
     3 ---(10)---- 6 ----(6)---- 7
     |\            | \         / |
     |(3)         (3) (8)__   /  |
     |  \          |       \ /   |
    (3)  4 --(3)-- 5   0    8   (2)
     |            /   / \   |   /
     |  ________(8) (3) (3)(3) /
     | /            /     \ | /
     2 ----(3)---- 1 -(12)- 9
    
    Shortest paths from 3
    3 -> 2 -> 1 -> 0 (dist=9)
    3 -> 2 -> 1 (dist=6)
    3 -> 2 (dist=3)
    3 -> 4 (dist=3)
    3 -> 4 -> 5 (dist=6)
    3 -> 4 -> 5 -> 6 (dist=9)
    3 -> 2 -> 1 -> 0 -> 9 -> 7 (dist=14)
    3 -> 2 -> 1 -> 0 -> 9 -> 8 (dist=15)
    3 -> 2 -> 1 -> 0 -> 9 (dist=12)
    */
    const graph = new WeightedGraph();
    graph.addVertex(0, { x: 3, y: 1 });
    graph.addVertex(1, { x: 2, y: 2 });
    graph.addVertex(2, { x: 0, y: 2 });
    graph.addVertex(3, { x: 0, y: 0 });
    graph.addVertex(4, { x: 1, y: 1 });
    graph.addVertex(5, { x: 2, y: 1 });
    graph.addVertex(6, { x: 2, y: 0 });
    graph.addVertex(7, { x: 5, y: 0 });
    graph.addVertex(8, { x: 4, y: 1 });
    graph.addVertex(9, { x: 4, y: 2 });
    graph.addEdge(0, 1, 3);
    graph.addEdge(0, 9, 3);
    graph.addEdge(1, 2, 3);
    graph.addEdge(1, 9, 12);
    graph.addEdge(2, 3, 3);
    graph.addEdge(2, 5, 8);
    graph.addEdge(3, 4, 3);
    graph.addEdge(3, 6, 10);
    graph.addEdge(4, 5, 3);
    graph.addEdge(5, 6, 3);
    graph.addEdge(6, 7, 6);
    graph.addEdge(6, 8, 8);
    graph.addEdge(7, 8, 3);
    graph.addEdge(7, 9, 2);
    graph.addEdge(8, 9, 3);

    const result0 = graph.dijkstra(3, [8]);
    const exp0 = { waypoints: [3, 2, 1, 0, 9, 8], legDist: 15 };
    assert.deepStrictEqual(result0, exp0, `Expected: ${exp0}\nbut got: ${result0}`);

    const result1 = graph.dijkstra(3, [1, 6, 8]);
    const exp1 = { waypoints: [3, 2, 1], legDist: 6 };
    assert.deepStrictEqual(result1, exp1, `Expected: ${exp1}\nbut got: ${result1}`);

    const result2 = graph.dijkstra(3, [0, 6, 8]);
    const exp2 = (result2.waypoints[-1] === 0)
      ? { waypoints: [3, 2, 1, 0], legDist: 9 } 
      : { waypoints: [3, 4, 5, 6], legDist: 9 };
    assert.deepStrictEqual(result2, exp2, `Expected: ${exp2}\nbut got: ${result2}`);

    const result3 = graph.dijkstra(3, [7, 8]);
    const exp3 = { waypoints: [3, 2, 1, 0, 9, 7], legDist: 14 };
    assert.deepStrictEqual(result3, exp3, `Expected: ${exp3}\nbut got: ${result3}`);  });
});
