/**
 * Global canvas configuration constants
 */
export const CANVAS_CONFIG = {
  METERS_PER_CELL: 1,
  DEFAULT_SNAP_INTERVAL: 0.1,
  PIXELS_PER_METER: 50,
  GRID_SIZE: 50 * 1,
  MIN_SCALE: 0.2,
  MAX_SCALE: 4,
  WALKWAY_NODE_RADIUS_PX: 6,
  WALKWAY_LINK_WIDTH_PX: 3,
  ROUTE_MODE_UNIT_OPACITY: 0.35,
};
