export const LOCATION_LAYOUT = {
  site: {
    name: "Clayton Campus",
    description: "Monash University main campus, Clayton VIC.",
  },

  floors: [
    {
      name: "Building 18 – Level 2 Storeroom",
      units: [
        {
          name: "Cabinet A",
          type: "cabinet",
          width: 2,
          height: 1.5,
          x: 1,
          y: 1,
          locations: [
            { name: "Shelf 1", code: "SC-A1", monthsAgo: 0 },
            { name: "Shelf 2", code: "SC-A2", monthsAgo: 1 },
          ],
        },
        {
          name: "Cabinet B",
          type: "cabinet",
          width: 2,
          height: 1.5,
          x: 4,
          y: 1,
          locations: [
            { name: "Shelf 1", code: "SC-B1", monthsAgo: 2 },
            { name: "Shelf 2", code: "SC-B2", monthsAgo: 4 },
          ],
        },
        {
          name: "Cabinet C",
          type: "cabinet",
          width: 2,
          height: 1.5,
          x: 7,
          y: 1,
          locations: [
            { name: "Shelf 1", code: "SC-C1", monthsAgo: 1 },
            { name: "Shelf 2", code: "SC-C2", monthsAgo: 3 },
          ],
        },
      ],
    },
    {
      name: "Building 67 – Ground Floor IT Room",
      units: [
        {
          name: "Equipment Rack 1",
          type: "rack",
          width: 1.5,
          height: 2.5,
          x: 1,
          y: 1,
          locations: [
            { name: "Bay 1", code: "IT-R1", monthsAgo: 5 },
            { name: "Bay 2", code: "IT-R2", monthsAgo: 7 },
          ],
        },
        {
          name: "Shelf A",
          type: "shelf",
          width: 2.5,
          height: 1,
          x: 3.5,
          y: 1,
          locations: [{ name: "Bay 1", code: "IT-S1", monthsAgo: 9 }],
        },
        {
          name: "Shelf B",
          type: "shelf",
          width: 2.5,
          height: 1,
          x: 3.5,
          y: 3,
          locations: [
            { name: "Bay 1", code: "IT-B1", monthsAgo: 2 },
            { name: "Bay 2", code: "IT-B2", monthsAgo: 4 },
          ],
        },
      ],
    },
    {
      name: "Building 3 – Ground Floor Storeroom",
      units: [
        {
          name: "Shelf A",
          type: "shelf",
          width: 3,
          height: 1,
          x: 1,
          y: 1,
          locations: [
            { name: "Bay 1", code: "SR-A1", monthsAgo: 11 },
            { name: "Bay 2", code: "SR-A2", monthsAgo: 12 },
          ],
        },
        {
          name: "Shelf B",
          type: "shelf",
          width: 3,
          height: 1,
          x: 1,
          y: 3,
          locations: [
            { name: "Bay 1", code: "SR-B1", monthsAgo: 3 },
            { name: "Bay 2", code: "SR-B2", monthsAgo: 6 },
          ],
        },
      ],
    },
    {
      name: "Building 6 – Facilities Warehouse",
      units: [
        {
          name: "Warehouse Shelving A",
          type: "shelf",
          width: 4,
          height: 1.5,
          x: 1,
          y: 1,
          locations: [
            { name: "Bay 1", code: "WH-A1", monthsAgo: 2 },
            { name: "Bay 2", code: "WH-A2", monthsAgo: 5 },
          ],
        },
        {
          name: "Warehouse Shelving B",
          type: "shelf",
          width: 4,
          height: 1.5,
          x: 1,
          y: 4,
          locations: [
            { name: "Bay 1", code: "WH-B1", monthsAgo: 1 },
            { name: "Bay 2", code: "WH-B2", monthsAgo: 8 },
          ],
        },
      ],
    },
    {
      name: "Building 75 – Learning & Teaching Building AV Store",
      units: [
        {
          name: "AV Cabinet 1",
          type: "cabinet",
          width: 2.5,
          height: 1.5,
          x: 1,
          y: 1,
          locations: [
            { name: "Shelf 1", code: "AV-1", monthsAgo: 2 },
            { name: "Shelf 2", code: "AV-2", monthsAgo: 3 },
          ],
        },
      ],
    },
    {
      name: "Building 32 – Sport & Recreation Centre Store",
      units: [
        {
          name: "Equipment Shelf",
          type: "shelf",
          width: 3,
          height: 1.5,
          x: 1,
          y: 1,
          locations: [
            { name: "Shelf 1", code: "SPT-1", monthsAgo: 4 },
            { name: "Shelf 2", code: "SPT-2", monthsAgo: 6 },
          ],
        },
      ],
    },
  ],
};

export const PRODUCT_RECORD_PLAN = [
  ["Lab Safety Goggles", "SC-A1", 35],
  ["Lab Safety Goggles", "SC-A2", 25],
  ["Nitrile Gloves (Box of 100)", "SC-A1", 20],
  ["Nitrile Gloves (Box of 100)", "SC-B1", 20],
  ["Safety Glasses (Clear, Anti-Fog)", "SC-C1", 25],
  ["Safety Glasses (Clear, Anti-Fog)", "SC-C2", 20],
  ["Lab Coat (White, Size L)", "SC-C1", 10],
  ["Lab Coat (White, Size L)", "SC-C2", 8],
  ["Chemical Spill Kit", "SC-C2", 6],
  ["Safety Face Shield", "SC-C1", 20],

  ["USB-A to USB-C Cable", "IT-R1", 20],
  ["USB-A to USB-C Cable", "IT-S1", 15],
  ["HDMI Cable (2m)", "IT-R1", 14],
  ["HDMI Cable (2m)", "IT-R2", 14],
  ["Ethernet Patch Cable (Cat6)", "IT-R1", 25],
  ["Ethernet Patch Cable (Cat6)", "IT-R2", 25],
  ["Wireless Mouse", "IT-B1", 15],
  ["Wireless Mouse", "IT-B2", 10],
  ["USB Hub (4-Port)", "IT-B1", 12],
  ["USB Hub (4-Port)", "IT-B2", 8],
  ["Webcam (1080p)", "IT-B2", 12],
  ["Wireless Keyboard", "IT-R2", 10],
  ["Wireless Keyboard", "IT-S1", 5],
  ["Laptop Docking Station", "IT-B1", 8],
  ['24" Monitor', "IT-B1", 6],
  ['24" Monitor', "IT-B2", 4],
  ["Laptop Stand (Adjustable)", "IT-B2", 14],

  ["Whiteboard Markers (Pack of 12)", "SR-A1", 18],
  ["Whiteboard Markers (Pack of 12)", "SR-A2", 12],
  ["A4 Copy Paper (Ream)", "SR-A1", 70],
  ["A4 Copy Paper (Ream)", "SR-A2", 50],
  ["Ballpoint Pens (Box of 50)", "SR-B1", 25],
  ["Ballpoint Pens (Box of 50)", "SR-B2", 15],
  ["Sticky Notes (Pack of 12)", "SR-B1", 15],
  ["Sticky Notes (Pack of 12)", "SR-B2", 10],
  ["Stapler (Standard)", "SR-B1", 18],
  ["Scissors (21cm)", "SR-B2", 22],
  ["Manila Folders (Box of 100)", "SR-B1", 9],
  ["Manila Folders (Box of 100)", "SR-B2", 7],

  ["Extension Power Board (6-outlet)", "IT-S1", 10],
  ["Extension Power Board (6-outlet)", "SR-A1", 12],
  ["Extension Cord (10m)", "WH-A1", 14],
  ["AA Batteries (Pack of 24)", "WH-A1", 35],
  ["AA Batteries (Pack of 24)", "WH-A2", 25],
  ["Surge Protector (4-outlet)", "WH-A2", 16],
  ["First Aid Kit", "SC-A2", 3],
  ["First Aid Kit", "SR-A2", 3],
  ["First Aid Kit", "IT-S1", 2],
  ["Hand Sanitizer (1L Pump)", "WH-A1", 18],
  ["Hand Sanitizer (1L Pump)", "WH-A2", 12],
  ["Hi-Vis Safety Vest", "WH-A2", 20],
  ["Hard Hat (Yellow)", "WH-A1", 15],
  ["Fire Extinguisher (2kg CO2)", "WH-A2", 10],

  ["Paper Towels (Pack of 16 Rolls)", "WH-B1", 24],
  ["Disinfectant Spray (750mL)", "WH-B1", 20],
  ["Disinfectant Spray (750mL)", "WH-B2", 16],
  ["Garbage Bags (Heavy Duty, 50pk)", "WH-B2", 20],
  ["Microfibre Mop", "WH-B1", 12],
  ["Glass Cleaner Spray (750mL)", "WH-B2", 28],

  ["Portable Projector", "AV-1", 6],
  ["Projector Screen (Portable, 1.8m)", "AV-1", 4],
  ["Projector Screen (Portable, 1.8m)", "AV-2", 4],
  ["Wireless Presenter Remote", "AV-2", 14],

  ["Basketball (Size 7)", "SPT-1", 12],
  ["Yoga Mat", "SPT-1", 10],
  ["Yoga Mat", "SPT-2", 10],
  ["Resistance Bands Set", "SPT-2", 16],
];
