export const PRODUCT_CATALOGUE = [
  {
    name: "Lab Safety Goggles",
    description: "ANSI-rated chemical splash goggles for laboratory use.",
    category: "Lab Safety",
    brand: "3M",
    sku: "PPE-GOG-001",
    unitCost: 12.5,
    totalQuantity: 60,
    reorderAt: 15,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Safety_Goggles.jpg/500px-Safety_Goggles.jpg",
  },
  {
    name: "Nitrile Gloves (Box of 100)",
    description: "Powder-free nitrile examination gloves, medium size.",
    category: "Lab Safety",
    brand: "Ansell",
    sku: "PPE-GLV-100M",
    unitCost: 18.9,
    totalQuantity: 40,
    reorderAt: 15,
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Disposable_nitrile_glove.jpg",
  },
  {
    name: "Safety Glasses (Clear, Anti-Fog)",
    description: "Clear polycarbonate anti-fog safety glasses with side shields.",
    category: "Lab Safety",
    brand: "3M",
    sku: "PPE-GLS-002",
    unitCost: 9.5,
    totalQuantity: 45,
    reorderAt: 15,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/UVEX_S3300_Genesis_XC_protective_eyewear.jpg/500px-UVEX_S3300_Genesis_XC_protective_eyewear.jpg",
  },
  {
    name: "Lab Coat (White, Size L)",
    description: "Flame-resistant cotton-blend laboratory coat, size large.",
    category: "Lab Safety",
    brand: "Livingstone",
    sku: "PPE-LAB-L",
    unitCost: 32.0,
    totalQuantity: 18,
    reorderAt: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Lab_coats.jpg/500px-Lab_coats.jpg",
  },
  {
    name: "Chemical Spill Kit",
    description: "Absorbent spill kit for general laboratory chemical spills.",
    category: "Lab Safety",
    brand: "Spilfyter",
    sku: "LAB-SPL-001",
    unitCost: 89.0,
    totalQuantity: 6,
    reorderAt: 2,
    image: null,
  },
  {
    name: "Safety Face Shield",
    description: "Full-face polycarbonate shield with adjustable headgear.",
    category: "Lab Safety",
    brand: "3M",
    sku: "PPE-FSH-001",
    unitCost: 14.0,
    totalQuantity: 20,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Zshield_Flex_Face_Shield%2C_designed_by_Scott_Henderson%2C_2020.jpg/500px-Zshield_Flex_Face_Shield%2C_designed_by_Scott_Henderson%2C_2020.jpg",
  },

  {
    name: "USB-A to USB-C Cable",
    description: "1.8m braided USB-A to USB-C charging and data cable.",
    category: "IT Accessories",
    brand: "Belkin",
    sku: "CBL-USBC-18",
    unitCost: 14.95,
    totalQuantity: 35,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/IKEA_SITTBRUNN_USB_A_TO_C_CABLE.jpg/500px-IKEA_SITTBRUNN_USB_A_TO_C_CABLE.jpg",
  },
  {
    name: "HDMI Cable (2m)",
    description: "High-speed HDMI 2.0 cable for display connections.",
    category: "IT Accessories",
    brand: "Belkin",
    sku: "CBL-HDMI-2M",
    unitCost: 19.95,
    totalQuantity: 28,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/HDMI_Cable.JPG/500px-HDMI_Cable.JPG",
  },
  {
    name: "Ethernet Patch Cable (Cat6)",
    description: "2m Cat6 RJ45 patch cable for network connections.",
    category: "IT Accessories",
    brand: "Belkin",
    sku: "CBL-CAT6-2M",
    unitCost: 8.5,
    totalQuantity: 50,
    reorderAt: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/UTP_Cat_6.jpg/500px-UTP_Cat_6.jpg",
  },
  {
    name: "Wireless Mouse",
    description: "Compact wireless optical mouse with USB nano receiver.",
    category: "IT Accessories",
    brand: "Logitech",
    sku: "ITE-MSE-WL01",
    unitCost: 29.0,
    totalQuantity: 25,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Logitech_M331_Silent_Mouse.jpg/500px-Logitech_M331_Silent_Mouse.jpg",
  },
  {
    name: "USB Hub (4-Port)",
    description: "Compact 4-port USB 3.0 hub for laptops and desktops.",
    category: "IT Accessories",
    brand: "Anker",
    sku: "ITE-HUB-4P",
    unitCost: 22.5,
    totalQuantity: 20,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2023_Hub_USB_2.0.jpg/500px-2023_Hub_USB_2.0.jpg",
  },
  {
    name: "Webcam (1080p)",
    description: "1080p USB webcam with built-in microphone for video calls.",
    category: "IT Accessories",
    brand: "Logitech",
    sku: "ITE-CAM-1080",
    unitCost: 45.0,
    totalQuantity: 12,
    reorderAt: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Webcam_%28Logitech_c922%29.jpg/500px-Webcam_%28Logitech_c922%29.jpg",
  },
  {
    name: "Wireless Keyboard",
    description: "Compact wireless keyboard with USB receiver.",
    category: "IT Equipment",
    brand: "Logitech",
    sku: "ITE-KBD-WL01",
    unitCost: 49.0,
    totalQuantity: 15,
    reorderAt: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Logitech_K380_CJK_Keyboard.jpg/500px-Logitech_K380_CJK_Keyboard.jpg",
  },
  {
    name: "Laptop Docking Station",
    description: "USB-C docking station with dual-monitor and Ethernet support.",
    category: "IT Equipment",
    brand: "Dell",
    sku: "ITE-DOC-001",
    unitCost: 189.0,
    totalQuantity: 8,
    reorderAt: 3,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Top_view_of_a_Dell_D-Dock_PD01X_with_docking_controls.jpg/500px-Top_view_of_a_Dell_D-Dock_PD01X_with_docking_controls.jpg",
  },
  {
    name: '24" Monitor',
    description: '24" 1080p IPS monitor for staff and lab workstations.',
    category: "IT Equipment",
    brand: "Dell",
    sku: "ITE-MON-24",
    unitCost: 219.0,
    totalQuantity: 10,
    reorderAt: 4,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Dell_Computer_Monitor.png/500px-Dell_Computer_Monitor.png",
  },
  {
    name: "Laptop Stand (Adjustable)",
    description: "Adjustable aluminium laptop stand for ergonomic desk setups.",
    category: "IT Equipment",
    brand: "Logitech",
    sku: "ITE-STD-001",
    unitCost: 39.0,
    totalQuantity: 14,
    reorderAt: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Laptop_stand.jpg/500px-Laptop_stand.jpg",
  },

  {
    name: "Whiteboard Markers (Pack of 12)",
    description: "Assorted colour dry-erase markers with chisel tip.",
    category: "Stationery",
    brand: "Artline",
    sku: "STA-MKR-12",
    unitCost: 11.2,
    totalQuantity: 30,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Whiteboard_Markers.jpg/500px-Whiteboard_Markers.jpg",
  },
  {
    name: "A4 Copy Paper (Ream)",
    description: "80gsm A4 copy paper, 500 sheets per ream.",
    category: "Stationery",
    brand: "Reflex",
    sku: "STA-PPR-A4",
    unitCost: 6.95,
    totalQuantity: 120,
    reorderAt: 40,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Stack_of_Copy_Paper.jpg/500px-Stack_of_Copy_Paper.jpg",
  },
  {
    name: "Ballpoint Pens (Box of 50)",
    description: "Medium-tip blue ballpoint pens, box of 50.",
    category: "Stationery",
    brand: "Bic",
    sku: "STA-PEN-50",
    unitCost: 9.9,
    totalQuantity: 40,
    reorderAt: 15,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Bic_4_couleurs.jpg/500px-Bic_4_couleurs.jpg",
  },
  {
    name: "Sticky Notes (Pack of 12)",
    description: "76x76mm sticky note pads, assorted colours, pack of 12.",
    category: "Stationery",
    brand: "Post-it",
    sku: "STA-STK-12",
    unitCost: 15.5,
    totalQuantity: 25,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Post-it.jpg/500px-Post-it.jpg",
  },
  {
    name: "Stapler (Standard)",
    description: "Full-strip standard desktop stapler.",
    category: "Stationery",
    brand: "Rexel",
    sku: "STA-STP-001",
    unitCost: 12.0,
    totalQuantity: 18,
    reorderAt: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Stapler_office.jpg/500px-Stapler_office.jpg",
  },
  {
    name: "Scissors (21cm)",
    description: "Stainless steel office scissors, 21cm.",
    category: "Stationery",
    brand: "Marbig",
    sku: "STA-SCI-021",
    unitCost: 6.5,
    totalQuantity: 22,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Scissors_01.jpg/500px-Scissors_01.jpg",
  },
  {
    name: "Manila Folders (Box of 100)",
    description: "Foolscap manila folders for physical filing, box of 100.",
    category: "Stationery",
    brand: "Marbig",
    sku: "STA-FLD-100",
    unitCost: 24.0,
    totalQuantity: 16,
    reorderAt: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Manila_Folders.jpg/500px-Manila_Folders.jpg",
  },

  {
    name: "Extension Power Board (6-outlet)",
    description: "6-outlet surge-protected power board with 1.8m cord.",
    category: "Electrical",
    brand: "HPM",
    sku: "ELE-PWR-6O",
    unitCost: 34.0,
    totalQuantity: 22,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Australian_10_A_Power_Board_with_Overload_Protection.jpg/500px-Australian_10_A_Power_Board_with_Overload_Protection.jpg",
  },
  {
    name: "Extension Cord (10m)",
    description: "10m heavy-duty extension cord, IP44 rated.",
    category: "Electrical",
    brand: "HPM",
    sku: "ELE-EXT-10M",
    unitCost: 28.0,
    totalQuantity: 14,
    reorderAt: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Yellow_extension_cord.jpg/500px-Yellow_extension_cord.jpg",
  },
  {
    name: "AA Batteries (Pack of 24)",
    description: "Alkaline AA batteries, pack of 24.",
    category: "Electrical",
    brand: "Energizer",
    sku: "ELE-BAT-AA24",
    unitCost: 13.5,
    totalQuantity: 60,
    reorderAt: 20,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Alkaline_AA_batteries.jpg/500px-Alkaline_AA_batteries.jpg",
  },
  {
    name: "Surge Protector (4-outlet)",
    description: "4-outlet surge protector with individual switches.",
    category: "Electrical",
    brand: "Belkin",
    sku: "ELE-SUR-4O",
    unitCost: 26.0,
    totalQuantity: 16,
    reorderAt: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Belkin-Surge-Protector.jpg/500px-Belkin-Surge-Protector.jpg",
  },
  {
    name: "First Aid Kit",
    description: "Workplace first aid kit compliant with AS2675 standards.",
    category: "Health & Safety",
    brand: "St John",
    sku: "HS-FAK-001",
    unitCost: 55.0,
    totalQuantity: 8,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/First_Aid_Kit_%28Frankfurt_am_Main%2C_18.02.2012%29.jpg/500px-First_Aid_Kit_%28Frankfurt_am_Main%2C_18.02.2012%29.jpg",
  },
  {
    name: "Hand Sanitizer (1L Pump)",
    description: "70% alcohol hand sanitizer, 1L pump bottle.",
    category: "Health & Safety",
    brand: "Dettol",
    sku: "HS-SAN-1L",
    unitCost: 11.0,
    totalQuantity: 30,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/University_Medical_Pharmaceuticals_Hand_Sanitizer_%28transparent_version%29.png",
  },
  {
    name: "Hi-Vis Safety Vest",
    description: "Day/night high-visibility safety vest, one size.",
    category: "Health & Safety",
    brand: "ProChoice",
    sku: "HS-VES-001",
    unitCost: 24.0,
    totalQuantity: 20,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Warnweste_gelb.jpg/500px-Warnweste_gelb.jpg",
  },
  {
    name: "Hard Hat (Yellow)",
    description: "Type 1 vented safety helmet, yellow.",
    category: "Health & Safety",
    brand: "3M",
    sku: "HS-HAT-001",
    unitCost: 18.0,
    totalQuantity: 15,
    reorderAt: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Yellow_hard_hat.jpg/500px-Yellow_hard_hat.jpg",
  },
  {
    name: "Fire Extinguisher (2kg CO2)",
    description: "2kg CO2 fire extinguisher for electrical fire risk areas.",
    category: "Health & Safety",
    brand: "Wormald",
    sku: "HS-EXT-2KG",
    unitCost: 65.0,
    totalQuantity: 10,
    reorderAt: 4,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/CO2_extinguisher_%289544108309%29.jpg/500px-CO2_extinguisher_%289544108309%29.jpg",
  },

  {
    name: "Paper Towels (Pack of 16 Rolls)",
    description: "2-ply paper towel rolls for kitchens and amenities, pack of 16.",
    category: "Cleaning Supplies",
    brand: "Kleenex",
    sku: "CLN-PTL-16",
    unitCost: 32.0,
    totalQuantity: 24,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Roll_of_Paper_Towels.jpg/500px-Roll_of_Paper_Towels.jpg",
  },
  {
    name: "Disinfectant Spray (750mL)",
    description: "Multi-surface disinfectant spray, 750mL.",
    category: "Cleaning Supplies",
    brand: "Glen 20",
    sku: "CLN-DIS-750",
    unitCost: 7.5,
    totalQuantity: 36,
    reorderAt: 12,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Savlon_Surface_disinfectant_spray.jpg/500px-Savlon_Surface_disinfectant_spray.jpg",
  },
  {
    name: "Garbage Bags (Heavy Duty, 50pk)",
    description: "Heavy-duty 120L garbage bags, pack of 50.",
    category: "Cleaning Supplies",
    brand: "Chux",
    sku: "CLN-BAG-50",
    unitCost: 14.0,
    totalQuantity: 20,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Black_garbage_bag.jpg/500px-Black_garbage_bag.jpg",
  },
  {
    name: "Microfibre Mop",
    description: "Flat microfibre mop with telescopic handle.",
    category: "Cleaning Supplies",
    brand: "Oates",
    sku: "CLN-MOP-001",
    unitCost: 22.0,
    totalQuantity: 12,
    reorderAt: 4,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Mikrofiber_Mop_40_cm.jpg/500px-Mikrofiber_Mop_40_cm.jpg",
  },
  {
    name: "Glass Cleaner Spray (750mL)",
    description: "Streak-free glass and surface cleaner spray, 750mL.",
    category: "Cleaning Supplies",
    brand: "Windex",
    sku: "CLN-GLS-750",
    unitCost: 6.9,
    totalQuantity: 28,
    reorderAt: 10,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Windex_%2848089717956%29.jpg/500px-Windex_%2848089717956%29.jpg",
  },

  {
    name: "Portable Projector",
    description: "Compact HD projector for lectures and presentations.",
    category: "AV Equipment",
    brand: "Epson",
    sku: "AV-PRJ-001",
    unitCost: 649.0,
    totalQuantity: 6,
    reorderAt: 2,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Sony_Portable_Ultra_Short_Throw_Projector_%2826089157293%29.jpg/500px-Sony_Portable_Ultra_Short_Throw_Projector_%2826089157293%29.jpg",
  },
  {
    name: "Projector Screen (Portable, 1.8m)",
    description: "Portable tripod projector screen, 1.8m diagonal.",
    category: "AV Equipment",
    brand: "Bosign",
    sku: "AV-SCR-180",
    unitCost: 129.0,
    totalQuantity: 8,
    reorderAt: 3,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Projector_Screen_stand.jpg/500px-Projector_Screen_stand.jpg",
  },
  {
    name: "Wireless Presenter Remote",
    description: "Wireless presenter remote with laser pointer.",
    category: "AV Equipment",
    brand: "Logitech",
    sku: "AV-REM-001",
    unitCost: 45.0,
    totalQuantity: 14,
    reorderAt: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Inateck_WP1002_Wireless_Presenter_%2816593914759%29.jpg/500px-Inateck_WP1002_Wireless_Presenter_%2816593914759%29.jpg",
  },
  {
    name: "Basketball (Size 7)",
    description: "Indoor/outdoor composite leather basketball, size 7.",
    category: "Sports & Recreation",
    brand: "Spalding",
    sku: "SPT-BSK-007",
    unitCost: 39.0,
    totalQuantity: 12,
    reorderAt: 4,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Spalding_Basketball.jpg/500px-Spalding_Basketball.jpg",
  },
  {
    name: "Yoga Mat",
    description: "6mm non-slip exercise yoga mat.",
    category: "Sports & Recreation",
    brand: "Gaiam",
    sku: "SPT-YOG-001",
    unitCost: 25.0,
    totalQuantity: 20,
    reorderAt: 8,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Yoga_mat.jpg/500px-Yoga_mat.jpg",
  },
  {
    name: "Resistance Bands Set",
    description: "Set of 5 latex resistance bands, varying tension.",
    category: "Sports & Recreation",
    brand: "Fitness Mad",
    sku: "SPT-RES-001",
    unitCost: 19.5,
    totalQuantity: 16,
    reorderAt: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Resistance_Band.jpg/500px-Resistance_Band.jpg",
  },
];
