export const mockItems = [
  {
    _id: "1",
    name: "AAA Battery Pack",
    tag: "electrical",
    description: "Alkaline rechargeable AAA battery pack (4-pack).",
    photoUrl:
      "https://www.duracell.com.au/upload/sites/26/2023/04/Web-PI-Rechargeable_PACKSHOTS_AU_RPP_AAA_4_BL_5000394047754_5006409_FOP.png",
    quantity: 50,
    currentStock: 50,
    lowStockThreshold: 10,
    reorderAt: 10,
    location: "Aisle 4 - Section 1",
    status: "OK",
    sku: "BAT-AAA-4",
    category: "electrical",
    brand: "Duracell",
    unitCost: 4.5,
    catalogImages: [
      "https://www.duracell.com.au/upload/sites/26/2023/04/Web-PI-Rechargeable_PACKSHOTS_AU_RPP_AAA_4_BL_5000394047754_5006409_FOP.png",
    ],
    qrCode: "",
  },
  {
    _id: "2",
    name: "Safety Helmet",
    tag: "safety",
    description: "Industrial safety helmet with adjustable strap.",
    photoUrl:
      "https://media.rs-online.com/image/upload/bo_1.5px_solid_white,b_auto,c_pad,dpr_2,f_auto,h_399,q_auto,w_710/c_pad,h_399,w_710/F1618136-01?pgw=1",
    quantity: 5,
    currentStock: 5,
    lowStockThreshold: 10,
    reorderAt: 10,
    location: "Aisle 3 - Section 2",
    status: "CRITICAL",
    sku: "SAFE-HELM-01",
    category: "safety",
    brand: "SafeGear",
    unitCost: 22.0,
    catalogImages: [
      "https://media.rs-online.com/image/upload/bo_1.5px_solid_white,b_auto,c_pad,dpr_2,f_auto,h_399,q_auto,w_710/c_pad,h_399,w_710/F1618136-01?pgw=1",
    ],
    qrCode: "",
  },
  {
    _id: "3",
    name: "Hard Hat Liner",
    tag: "safety",
    description: "Replacement liner for hard hats.",
    photoUrl: "https://www.example.com/images/liner.png",
    quantity: 0,
    currentStock: 0,
    lowStockThreshold: 5,
    reorderAt: 5,
    location: "Aisle 3 - Section 3",
    status: "CRITICAL",
    sku: "LINER-001",
    category: "safety",
    brand: "SafeGear",
    unitCost: 3.5,
    catalogImages: ["https://www.example.com/images/liner.png"],
    qrCode: "",
  },
  {
    _id: "4",
    name: "Work Gloves",
    tag: "safety",
    description: "General purpose work gloves.",
    photoUrl: "https://www.example.com/images/gloves.png",
    quantity: 25,
    currentStock: 25,
    lowStockThreshold: 25,
    reorderAt: 10,
    location: "Aisle 2 - Section 1",
    status: "OK",
    sku: "GLOVES-01",
    category: "safety",
    brand: "Handy",
    unitCost: 6.0,
    catalogImages: ["https://www.example.com/images/gloves.png"],
    qrCode: "",
  },
  {
    _id: "5",
    name: "Steel Toe Boots",
    tag: "safety",
    description: "Durable steel-toe work boots.",
    photoUrl: "https://www.example.com/images/boots.png",
    quantity: 100,
    currentStock: 100,
    lowStockThreshold: 20,
    reorderAt: 50,
    location: "Aisle 1 - Section 4",
    status: "OK",
    sku: "BOOTS-STEEL-01",
    category: "safety",
    brand: "BootWorks",
    unitCost: 85.0,
    catalogImages: ["https://www.example.com/images/boots.png"],
    qrCode: "",
  },
  {
    _id: "6",
    name: "Hex bolts M8",
    tag: "fasteners",
    description: "M8 hex bolts, stainless steel.",
    photoUrl: "https://www.example.com/images/bolts.png",
    quantity: 4,
    currentStock: 4,
    lowStockThreshold: 25,
    reorderAt: 100,
    location: "Cabinet 2",
    status: "CRITICAL",
    sku: "BOLT-M8-SS",
    category: "fasteners",
    brand: "FastenRight",
    unitCost: 0.12,
    catalogImages: ["https://www.example.com/images/bolts.png"],
    qrCode: "",
  },
  {
    _id: "7",
    name: "Wood screws",
    tag: "fasteners",
    description: "Assorted wood screws.",
    photoUrl: "https://www.example.com/images/screws.png",
    quantity: 0,
    currentStock: 0,
    lowStockThreshold: 50,
    reorderAt: 200,
    location: "Drawer 3",
    status: "CRITICAL",
    sku: "SCREW-WOOD-ASSORT",
    category: "fasteners",
    brand: "FastenRight",
    unitCost: 0.05,
    catalogImages: ["https://www.example.com/images/screws.png"],
    qrCode: "",
  },
  {
    _id: "8",
    name: "Cable ties 200mm",
    tag: "misc",
    description: "200mm nylon cable ties, pack of 100.",
    photoUrl: "https://www.example.com/images/ties.png",
    quantity: 3,
    currentStock: 3,
    lowStockThreshold: 30,
    reorderAt: 100,
    location: "Bin 2",
    status: "CRITICAL",
    sku: "TIE-200-100",
    category: "misc",
    brand: "TiePro",
    unitCost: 2.5,
    catalogImages: ["https://www.example.com/images/ties.png"],
    qrCode: "",
  },
];

export function getMockItemById(itemId) {
  return mockItems.find((item) => item._id === itemId);
}

export function getLowStockItems(items) {
  return items.filter(
    (i) =>
      typeof i.quantity === "number" &&
      typeof i.lowStockThreshold === "number" &&
      i.quantity <= i.lowStockThreshold,
  );
}

export function getTotalValue(items) {
  return items.reduce((total, item) => {
    return total + (item.unitCost * item.quantity || 0);
  }, 0);
}